### ISSUE TITLE
Vite 4.0 support

### ISSUE THREAD

**Issue by haltcase** [bienzaaron/vite-plugin-inline-source#192]
I've installed this to use it with Vite 4.0 but doing so requires using npm's `--legacy-peer-deps` flag to bypass errors. I'm not familiar with plugin interface changes between Vite 3 and 4, so I don't know if it's as simple as updating the peer dep range. However, it seems to be working in my testing so far.

https://github.com/bienzaaron/vite-plugin-inline-source/blob/9a4f4322ea529ee9d847b987527fd38f48cfa459/package.json#L55-L57

I'd be willing to open a PR for this change.

**Comment by bienzaaron** [comment]
As far as I can tell, the only change would be updating the peer dep range. A PR would be welcome 🙂

**Comment by bienzaaron** [comment]
I think `rollup` will need bumped to 3.x alongside vite 4.x.

**Comment by bienzaaron** [comment]
released in [v2.2.0](https://github.com/bienzaaron/vite-plugin-inline-source/releases/tag/v2.2.0)

**Comment by haltcase** [comment]
I'm not so sure this is fixed. Production builds still fail, I think because Vite does not expose Rollup's `context.load` method.

```
rendering chunks (6)...[vite:build-html] ctx.load is not a function
error during build:
TypeError: ctx.load is not a function
    at /workspaces/project/node_modules/vite-plugin-inline-source/dist/index.js:43:28
    at transformIndexHtml (/workspaces/project/node_modules/vite-plugin-inline-source/dist/index.js:73:20)
    at applyHtmlTransforms (file:///workspaces/project/node_modules/vite/dist/node/chunks/dep-3007b26d.js:35968:27)
    at Object.generateBundle (file:///workspaces/project/node_modules/vite/dist/node/chunks/dep-3007b26d.js:35875:32)
    at file:///workspaces/project/node_modules/rollup/dist/es/shared/rollup.js:23891:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

For what it's worth, I had started a PR to fix this but ran into issues related to missing test files and such that are not committed to version control. I settled for using `patch-package` with the following diff:

<details>
<summary>
patch diff
</summary>

diff --git a/node_modules/vite-plugin-inline-source/dist/index.js b/node_modules/vite-plugin-inline-source/dist/index.js
index 3dafedb..dc210cf 100644
--- a/node_modules/vite-plugin-inline-source/dist/index.js
+++ b/node_modules/vite-plugin-inline-source/dist/index.js
@@ -21,7 +21,7 @@ const InlineSourceOptionsSchema = zod_1.default
 })
     .default({});
 const PATTERN = /<([A-z0-9-]+)\s+([^>]*?)src\s*=\s*"([^>]*?)"([^>]*?)\s*((\/>)|(>\s*<\/\s*\1\s*>))/gi;
-const getTransformFunction = (options) => async (source, ctx, id) => {
+const getTransformFunction = (options) => async (source, ctx, id, root) => {
     if (id && !id.endsWith(".html")) {
         return source;
     }
@@ -37,11 +37,11 @@ const getTransformFunction = (options) => async (source, ctx, id) => {
         if ((isImg && !isSvgFile) || !shouldInline) {
             continue;
         }
-        let fileContent = ctx.server
-            ? (await (0, promises_1.readFile)(`${ctx.server.config.root}/${fileName}`)).toString()
-            : // @ts-expect-error don't know these types aren't right
-                (await ctx.load({ id: `${fileName}?raw` })).ast?.body?.[0].declaration
-                    .value;
+
+        const projectRoot = root ?? ctx.server.config.root ?? "";
+        const filePath = node_path_1.default.join(projectRoot, fileName);
+
+        let fileContent = (await (0, promises_1.readFile)(filePath)).toString();
         if (isSvgFile && options.optimizeSvgs) {
             fileContent = (0, svgo_1.optimize)(fileContent, options.svgoOptions).data;
         }
@@ -64,13 +64,18 @@ const getTransformFunction = (options) => async (source, ctx, id) => {
 };
 function VitePluginInlineSource(opts) {
     const transformHtml = getTransformFunction(InlineSourceOptionsSchema.parse(opts));
+    let root;
+
     return {
         name: "vite-plugin-inline-source",
+        configResolved(ctx) {
+            root = ctx.root;
+        },
         transform(source, id) {
             return transformHtml(source, this, id);
         },
-        transformIndexHtml(source, ctx) {
-            return transformHtml(source, ctx);
+        async transformIndexHtml(source, ctx) {
+            return transformHtml(source, ctx, undefined, root);
         },
     };
 }
</details>

**Comment by bienzaaron** [comment]
Curious if you have a reproduction? I'm using it just fine with Vite 4 in a couple projects with no issues accessing Rollup's `context.load`. There's also a super simple stackblitz in the readme, can run `build` there with no problems.



I'm also curious as to what errors you're getting with the tests.
running:
```
mkdir scratch && cd scratch
git clone https://github.com/bienzaaron/vite-plugin-inline-source.git
cd vite-plugin-inline-source
npm i && npm run test
```
works fine for me on Mac. Produces the following output:
<spoiler>
<details>

```
❯ mkdir scratch && cd scratch
git clone https://github.com/bienzaaron/vite-plugin-inline-source.git
cd vite-plugin-inline-source
npm i && npm run test
Cloning into 'vite-plugin-inline-source'...
remote: Enumerating objects: 502, done.
remote: Counting objects: 100% (241/241), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 502 (delta 221), reused 213 (delta 198), pack-reused 261
Receiving objects: 100% (502/502), 315.61 KiB | 6.44 MiB/s, done.
Resolving deltas: 100% (303/303), done.

added 270 packages, and audited 271 packages in 2s

67 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> vite-plugin-inline-source@2.2.0 test
> vitest run --coverage


 RUN  v0.29.2 /Users/ajb/scratch/scratch/vite-plugin-inline-source
      Coverage enabled with c8

stdout | src/__tests__/index.spec.ts > it then inlines css and preserves style tags
vite v4.1.4 building for production...

stdout | src/__tests__/index.spec.ts > it then inlines css and preserves style tags
transforming...

stderr | src/__tests__/index.spec.ts > it then inlines css and preserves style tags
Generated an empty chunk: "index".

stdout | src/__tests__/index.spec.ts > it then inlines css and preserves style tags
✓ 3 modules transformed.

stderr | src/__tests__/index.spec.ts > it then inlines css and preserves style tags
<empty line>
stdout | src/__tests__/index.spec.ts > it then inlines css and preserves style tags
rendering chunks...

stderr | src/__tests__/index.spec.ts > it then inlines css and preserves style tags
<empty line>
stdout | src/__tests__/index.spec.ts > it then inlines css and preserves style tags
computing gzip size...

stderr | src/__tests__/index.spec.ts > it then inlines css and preserves style tags
<empty line>
stdout | src/__tests__/index.spec.ts > it then inlines css and preserves style tags
dist/index.html  0.11 kB
dist/style.css   0.03 kB │ gzip: 0.05 kB

stdout | src/__tests__/index.spec.ts > it then doesn't mess with tags it shouldn't mess with
vite v4.1.4 building for production...

stdout | src/__tests__/index.spec.ts > it then doesn't mess with tags it shouldn't mess with
transforming...

stderr | src/__tests__/index.spec.ts > it then doesn't mess with tags it shouldn't mess with
Generated an empty chunk: "index".

stdout | src/__tests__/index.spec.ts > it then doesn't mess with tags it shouldn't mess with
✓ 3 modules transformed.
rendering chunks...

stderr | src/__tests__/index.spec.ts > it then doesn't mess with tags it shouldn't mess with
<empty line>
stdout | src/__tests__/index.spec.ts > it then doesn't mess with tags it shouldn't mess with
computing gzip size...
dist/index.html  0.13 kB
dist/style.css   0.03 kB │ gzip: 0.05 kB

stdout | src/__tests__/index.spec.ts > it then inlines svg
vite v4.1.4 building for production...

stderr | src/__tests__/index.spec.ts > it then inlines svg
Generated an empty chunk: "index".

stdout | src/__tests__/index.spec.ts > it then inlines svg
transforming...
✓ 2 modules transformed.

stderr | src/__tests__/index.spec.ts > it then inlines svg
<empty line>
stdout | src/__tests__/index.spec.ts > it then inlines svg
rendering chunks...
dist/i-am-an-svg.svg  0.07 kB
dist/index.html       0.10 kB

stdout | src/__tests__/index.spec.ts > it then optimizes svg with default options
vite v4.1.4 building for production...

stderr | src/__tests__/index.spec.ts > it then optimizes svg with default options
Generated an empty chunk: "index".

stdout | src/__tests__/index.spec.ts > it then optimizes svg with default options
transforming...
✓ 2 modules transformed.
rendering chunks...

stderr | src/__tests__/index.spec.ts > it then optimizes svg with default options
<empty line>
stdout | src/__tests__/index.spec.ts > it then optimizes svg with default options
dist/i-am-an-svg.svg  0.07 kB
dist/index.html       0.10 kB

stdout | src/__tests__/index.spec.ts > it then optimizes svg with custom options
vite v4.1.4 building for production...
vite v4.1.4 building for production...

stderr | src/__tests__/index.spec.ts > it then optimizes svg with custom options
[vite-plugin-inline-source] <input>:1:35: Attribute without value
file: /Users/ajb/scratch/scratch/vite-plugin-inline-source/src/__tests__/index.html

stdout | src/__tests__/index.spec.ts > it then optimizes svg with custom options
transforming...
✓ 1 modules transformed.

stdout | src/__tests__/index.spec.ts > it then optimizes svg with custom options
transforming...
✓ 2 modules transformed.
rendering chunks...

stderr | src/__tests__/index.spec.ts > it then optimizes svg with custom options
Generated an empty chunk: "index".

stderr | src/__tests__/index.spec.ts > it then optimizes svg with custom options
<empty line>
stdout | src/__tests__/index.spec.ts > it then optimizes svg with custom options
dist/index.html       0.10 kB
dist/i-am-an-svg.svg  0.18 kB

stdout | src/__tests__/index.spec.ts > custom replaceTags
vite v4.1.4 building for production...

stderr | src/__tests__/index.spec.ts > custom replaceTags
Generated an empty chunk: "index".

stdout | src/__tests__/index.spec.ts > custom replaceTags
transforming...
✓ 2 modules transformed.
rendering chunks...

stderr | src/__tests__/index.spec.ts > custom replaceTags
<empty line>
stdout | src/__tests__/index.spec.ts > custom replaceTags
dist/abc.html    0.01 kB
dist/index.html  0.02 kB

 ✓ src/__tests__/index.spec.ts (7)

 Test Files  1 passed (1)
      Tests  7 passed (7)
   Start at  13:56:22
   Duration  435ms (transform 50ms, setup 0ms, collect 158ms, tests 107ms)

JSON report written to /Users/ajb/scratch/scratch/vite-plugin-inline-source/test-report.json
 % Coverage report from c8
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |
----------|---------|----------|---------|---------|-------------------
```

</details>
</spoiler>

**Comment by bienzaaron** [comment]
Though I do see https://github.com/vitejs/vite/pull/11469, which would imply that it shouldn't be accessible from the plugin context 🤔

**Comment by haltcase** [comment]
I'm trying to replicate my exact error on Stackblitz. I haven't quite gotten there, but was able to at least demonstrate what seems to be an issue with resolving files when there's a custom `root` defined:

https://stackblitz.com/edit/vite-ysw8ui?file=vite.config.js

**Comment by bienzaaron** [comment]
custom roots should work with [v2.2.2](https://github.com/bienzaaron/vite-plugin-inline-source/releases/tag/v2.2.2)

**Comment by haltcase** [comment]
@bienzaaron unfortunately, v2.2.2 doesn't resolve this for me and still requires my patch [mentioned here](https://github.com/bienzaaron/vite-plugin-inline-source/issues/192#issuecomment-1453909229) that removes the use of `ctx.load`.

I had started working on a PR to incorporate it, but since I'm not familiar with Vite's asset pipeline I struggled with the tests. Either the tests generate files in a different way than the normal Vite processes or my patch is only a partial solution (though it works in both dev & production for me).

```
rendering chunks (6)...[vite:build-html] ctx.load is not a function
error during build:
TypeError: ctx.load is not a function
    at transformHtml (/workspaces/triviatime-womens-health/node_modules/vite-plugin-inline-source/dist/index.js:47:32)
    at transformIndexHtml (/workspaces/triviatime-womens-health/node_modules/vite-plugin-inline-source/dist/index.js:78:20)
    at applyHtmlTransforms (file:///workspaces/triviatime-womens-health/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:37685:27)
    at Object.generateBundle (file:///workspaces/triviatime-womens-health/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:37559:32)
    at file:///workspaces/triviatime-womens-health/node_modules/rollup/dist/es/shared/node-entry.js:24551:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
